// Code generated by protoc-gen-go. DO NOT EDIT.
// source: seer.proto

/*
Package seer is a generated protocol buffer package.

It is generated from these files:
	seer.proto

It has these top-level messages:
	Stream
	Event
	Interval
	Forecast
	CreateStreamRequest
	GetStreamRequest
	DeleteStreamRequest
	ListStreamsRequest
	ListStreamsResponse
	UpdateStreamRequest
	GetForecastRequest
*/
package seer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Domain int32

const (
	Domain_CONTINUOUS          Domain = 0
	Domain_CONTINUOUS_RIGHT    Domain = 1
	Domain_CONTINUOUS_INTERVAL Domain = 2
	Domain_DISCRETE_RIGHT      Domain = 3
	Domain_DISCRETE_INTERVAL   Domain = 4
)

var Domain_name = map[int32]string{
	0: "CONTINUOUS",
	1: "CONTINUOUS_RIGHT",
	2: "CONTINUOUS_INTERVAL",
	3: "DISCRETE_RIGHT",
	4: "DISCRETE_INTERVAL",
}
var Domain_value = map[string]int32{
	"CONTINUOUS":          0,
	"CONTINUOUS_RIGHT":    1,
	"CONTINUOUS_INTERVAL": 2,
	"DISCRETE_RIGHT":      3,
	"DISCRETE_INTERVAL":   4,
}

func (x Domain) String() string {
	return proto.EnumName(Domain_name, int32(x))
}
func (Domain) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// A data stream
type Stream struct {
	Name          string                      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Period        float64                     `protobuf:"fixed64,2,opt,name=period" json:"period,omitempty"`
	LastEventTime *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=last_event_time,json=lastEventTime" json:"last_event_time,omitempty"`
	Domain        Domain                      `protobuf:"varint,4,opt,name=domain,enum=seer.Domain" json:"domain,omitempty"`
	Min           float64                     `protobuf:"fixed64,5,opt,name=min" json:"min,omitempty"`
	Max           float64                     `protobuf:"fixed64,6,opt,name=max" json:"max,omitempty"`
}

func (m *Stream) Reset()                    { *m = Stream{} }
func (m *Stream) String() string            { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()               {}
func (*Stream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetPeriod() float64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Stream) GetLastEventTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastEventTime
	}
	return nil
}

func (m *Stream) GetDomain() Domain {
	if m != nil {
		return m.Domain
	}
	return Domain_CONTINUOUS
}

func (m *Stream) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Stream) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

// A set of ordered events (values and times) in a stream
type Event struct {
	Times  []*google_protobuf1.Timestamp `protobuf:"bytes,1,rep,name=times" json:"times,omitempty"`
	Values []float64                     `protobuf:"fixed64,2,rep,packed,name=values" json:"values,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetTimes() []*google_protobuf1.Timestamp {
	if m != nil {
		return m.Times
	}
	return nil
}

func (m *Event) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

// A confidence interval
type Interval struct {
	Probability float64   `protobuf:"fixed64,1,opt,name=probability" json:"probability,omitempty"`
	LowerBound  []float64 `protobuf:"fixed64,2,rep,packed,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	UpperBound  []float64 `protobuf:"fixed64,3,rep,packed,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
}

func (m *Interval) Reset()                    { *m = Interval{} }
func (m *Interval) String() string            { return proto.CompactTextString(m) }
func (*Interval) ProtoMessage()               {}
func (*Interval) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Interval) GetProbability() float64 {
	if m != nil {
		return m.Probability
	}
	return 0
}

func (m *Interval) GetLowerBound() []float64 {
	if m != nil {
		return m.LowerBound
	}
	return nil
}

func (m *Interval) GetUpperBound() []float64 {
	if m != nil {
		return m.UpperBound
	}
	return nil
}

// A forecast, with point predictions and confidence intervals
type Forecast struct {
	Times     []*google_protobuf1.Timestamp `protobuf:"bytes,1,rep,name=times" json:"times,omitempty"`
	Values    []float64                     `protobuf:"fixed64,2,rep,packed,name=values" json:"values,omitempty"`
	Intervals []*Interval                   `protobuf:"bytes,3,rep,name=intervals" json:"intervals,omitempty"`
}

func (m *Forecast) Reset()                    { *m = Forecast{} }
func (m *Forecast) String() string            { return proto.CompactTextString(m) }
func (*Forecast) ProtoMessage()               {}
func (*Forecast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Forecast) GetTimes() []*google_protobuf1.Timestamp {
	if m != nil {
		return m.Times
	}
	return nil
}

func (m *Forecast) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Forecast) GetIntervals() []*Interval {
	if m != nil {
		return m.Intervals
	}
	return nil
}

// The request message containing the stream to be created
type CreateStreamRequest struct {
	Stream *Stream `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
}

func (m *CreateStreamRequest) Reset()                    { *m = CreateStreamRequest{} }
func (m *CreateStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStreamRequest) ProtoMessage()               {}
func (*CreateStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateStreamRequest) GetStream() *Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

// The request message containing the name of the requested stream
type GetStreamRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetStreamRequest) Reset()                    { *m = GetStreamRequest{} }
func (m *GetStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStreamRequest) ProtoMessage()               {}
func (*GetStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The request message containing the name of the stream to be deleted
type DeleteStreamRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteStreamRequest) Reset()                    { *m = DeleteStreamRequest{} }
func (m *DeleteStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteStreamRequest) ProtoMessage()               {}
func (*DeleteStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The request message containing the paging data for the stream to list
type ListStreamsRequest struct {
	PageSize   int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageNumber int32 `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
}

func (m *ListStreamsRequest) Reset()                    { *m = ListStreamsRequest{} }
func (m *ListStreamsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListStreamsRequest) ProtoMessage()               {}
func (*ListStreamsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListStreamsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListStreamsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

// The response message containing a list of streams
type ListStreamsResponse struct {
	Streams []*Stream `protobuf:"bytes,1,rep,name=streams" json:"streams,omitempty"`
}

func (m *ListStreamsResponse) Reset()                    { *m = ListStreamsResponse{} }
func (m *ListStreamsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListStreamsResponse) ProtoMessage()               {}
func (*ListStreamsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListStreamsResponse) GetStreams() []*Stream {
	if m != nil {
		return m.Streams
	}
	return nil
}

// The request message containing events to apply to the stream
type UpdateStreamRequest struct {
	Event *Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *UpdateStreamRequest) Reset()                    { *m = UpdateStreamRequest{} }
func (m *UpdateStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateStreamRequest) ProtoMessage()               {}
func (*UpdateStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateStreamRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *UpdateStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The request message containing the forecast length
type GetForecastRequest struct {
	N int32 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
}

func (m *GetForecastRequest) Reset()                    { *m = GetForecastRequest{} }
func (m *GetForecastRequest) String() string            { return proto.CompactTextString(m) }
func (*GetForecastRequest) ProtoMessage()               {}
func (*GetForecastRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetForecastRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func init() {
	proto.RegisterType((*Stream)(nil), "seer.Stream")
	proto.RegisterType((*Event)(nil), "seer.Event")
	proto.RegisterType((*Interval)(nil), "seer.Interval")
	proto.RegisterType((*Forecast)(nil), "seer.Forecast")
	proto.RegisterType((*CreateStreamRequest)(nil), "seer.CreateStreamRequest")
	proto.RegisterType((*GetStreamRequest)(nil), "seer.GetStreamRequest")
	proto.RegisterType((*DeleteStreamRequest)(nil), "seer.DeleteStreamRequest")
	proto.RegisterType((*ListStreamsRequest)(nil), "seer.ListStreamsRequest")
	proto.RegisterType((*ListStreamsResponse)(nil), "seer.ListStreamsResponse")
	proto.RegisterType((*UpdateStreamRequest)(nil), "seer.UpdateStreamRequest")
	proto.RegisterType((*GetForecastRequest)(nil), "seer.GetForecastRequest")
	proto.RegisterEnum("seer.Domain", Domain_name, Domain_value)
}

func init() { proto.RegisterFile("seer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xf3, 0x45, 0x33, 0x0e, 0x21, 0x4c, 0xa0, 0xb8, 0xe9, 0xa1, 0xc6, 0x42, 0x55, 0x40,
	0x28, 0x45, 0xe9, 0xa9, 0x42, 0x1c, 0x68, 0x12, 0x4a, 0xa4, 0x2a, 0x15, 0x9b, 0x94, 0x6b, 0xe4,
	0x90, 0xa1, 0xb2, 0xe4, 0x2f, 0xec, 0x4d, 0x69, 0x7b, 0xe4, 0xa7, 0xf1, 0xa7, 0xb8, 0xa2, 0xdd,
	0xf5, 0xa6, 0x4e, 0x13, 0x89, 0x0b, 0xb7, 0xdd, 0x37, 0x6f, 0x66, 0xfc, 0x66, 0xde, 0x1a, 0x20,
	0x25, 0x4a, 0xba, 0x71, 0x12, 0xf1, 0x08, 0xcb, 0xe2, 0xdc, 0xde, 0xbf, 0x8a, 0xa2, 0x2b, 0x9f,
	0x8e, 0x24, 0x36, 0x5f, 0x7e, 0x3f, 0xa2, 0x20, 0xe6, 0xb7, 0x8a, 0xd2, 0x3e, 0x78, 0x18, 0xe4,
	0x5e, 0x40, 0x29, 0x77, 0x83, 0x58, 0x11, 0x9c, 0xdf, 0x06, 0x54, 0x27, 0x3c, 0x21, 0x37, 0x40,
	0x84, 0x72, 0xe8, 0x06, 0x64, 0x19, 0xb6, 0xd1, 0xa9, 0x31, 0x79, 0xc6, 0x5d, 0xa8, 0xc6, 0x94,
	0x78, 0xd1, 0xc2, 0x2a, 0xda, 0x46, 0xc7, 0x60, 0xd9, 0x0d, 0x4f, 0xe1, 0x89, 0xef, 0xa6, 0x7c,
	0x46, 0xd7, 0x14, 0xf2, 0x99, 0x28, 0x6a, 0x95, 0x6c, 0xa3, 0x63, 0xf6, 0xda, 0x5d, 0xd5, 0xb1,
	0xab, 0x3b, 0x76, 0xa7, 0xba, 0x23, 0x7b, 0x2c, 0x52, 0x86, 0x22, 0x43, 0x60, 0xf8, 0x0a, 0xaa,
	0x8b, 0x28, 0x70, 0xbd, 0xd0, 0x2a, 0xdb, 0x46, 0xa7, 0xd1, 0xab, 0x77, 0xa5, 0xb6, 0x81, 0xc4,
	0x58, 0x16, 0xc3, 0x26, 0x94, 0x02, 0x2f, 0xb4, 0x2a, 0xb2, 0xbd, 0x38, 0x4a, 0xc4, 0xbd, 0xb1,
	0xaa, 0x19, 0xe2, 0xde, 0x38, 0x5f, 0xa0, 0x22, 0xcb, 0xe2, 0x3b, 0xa8, 0x48, 0x81, 0x96, 0x61,
	0x97, 0xfe, 0xf1, 0x31, 0x8a, 0x28, 0x04, 0x5e, 0xbb, 0xfe, 0x92, 0x52, 0xab, 0x68, 0x97, 0x84,
	0x40, 0x75, 0x73, 0x42, 0xd8, 0x19, 0x85, 0x9c, 0x92, 0x6b, 0xd7, 0x47, 0x1b, 0xcc, 0x38, 0x89,
	0xe6, 0xee, 0xdc, 0xf3, 0x3d, 0x7e, 0x2b, 0xe7, 0x63, 0xb0, 0x3c, 0x84, 0x07, 0x60, 0xfa, 0xd1,
	0x4f, 0x4a, 0x66, 0xf3, 0x68, 0x19, 0x2e, 0xb2, 0x52, 0x20, 0xa1, 0x53, 0x81, 0x08, 0xc2, 0x32,
	0x8e, 0x57, 0x84, 0x92, 0x22, 0x48, 0x48, 0x12, 0x9c, 0x5f, 0x06, 0xec, 0x7c, 0x8a, 0x12, 0xfa,
	0xe6, 0xa6, 0xff, 0x51, 0x06, 0xbe, 0x85, 0x9a, 0x97, 0xc9, 0x48, 0x65, 0x57, 0xb3, 0xd7, 0x50,
	0x63, 0xd6, 0xea, 0xd8, 0x3d, 0xc1, 0x79, 0x0f, 0xad, 0x7e, 0x42, 0x2e, 0x27, 0xe5, 0x08, 0x46,
	0x3f, 0x96, 0x94, 0x72, 0xb1, 0xa8, 0x54, 0x02, 0x52, 0xba, 0xa9, 0x17, 0x95, 0x91, 0xb2, 0x98,
	0x73, 0x08, 0xcd, 0x33, 0xe2, 0xeb, 0x99, 0x5b, 0x2c, 0xe5, 0xbc, 0x86, 0xd6, 0x80, 0x7c, 0x7a,
	0xd8, 0x64, 0x1b, 0x95, 0x01, 0x9e, 0x7b, 0x69, 0x56, 0x33, 0xd5, 0xcc, 0x7d, 0xa8, 0xc5, 0xee,
	0x15, 0xcd, 0x52, 0xef, 0x4e, 0xd1, 0x2b, 0x6c, 0x47, 0x00, 0x13, 0xef, 0x8e, 0xc4, 0xa0, 0x65,
	0x30, 0x5c, 0x06, 0x73, 0x4a, 0xa4, 0x6b, 0x2b, 0x0c, 0x04, 0x34, 0x96, 0x88, 0xf3, 0x01, 0x5a,
	0x6b, 0x35, 0xd3, 0x38, 0x0a, 0x53, 0xc2, 0x43, 0x78, 0xa4, 0x74, 0xe8, 0xa1, 0xaf, 0x8b, 0xd4,
	0x41, 0xe7, 0x1c, 0x5a, 0x97, 0xf1, 0x62, 0x63, 0x44, 0x2f, 0xa1, 0x22, 0x9f, 0x42, 0x36, 0x21,
	0x53, 0x25, 0x4b, 0x53, 0x32, 0x15, 0x59, 0x09, 0x2c, 0xe6, 0x04, 0x3a, 0x80, 0x67, 0xc4, 0xf5,
	0xde, 0x75, 0xb1, 0x3a, 0x18, 0x61, 0x26, 0xcc, 0x08, 0xdf, 0x24, 0x50, 0x55, 0x4f, 0x02, 0x1b,
	0x00, 0xfd, 0x8b, 0xf1, 0x74, 0x34, 0xbe, 0xbc, 0xb8, 0x9c, 0x34, 0x0b, 0xf8, 0x0c, 0x9a, 0xf7,
	0xf7, 0x19, 0x1b, 0x9d, 0x7d, 0x9e, 0x36, 0x0d, 0x7c, 0x01, 0xad, 0x1c, 0x3a, 0x1a, 0x4f, 0x87,
	0xec, 0xeb, 0xc7, 0xf3, 0x66, 0x11, 0x11, 0x1a, 0x83, 0xd1, 0xa4, 0xcf, 0x86, 0xd3, 0x61, 0x46,
	0x2e, 0xe1, 0x73, 0x78, 0xba, 0xc2, 0x56, 0xd4, 0x72, 0xef, 0x4f, 0x11, 0xca, 0x13, 0xa2, 0x04,
	0x4f, 0xa0, 0x9e, 0x77, 0x04, 0xee, 0x29, 0x61, 0x5b, 0x5c, 0xd2, 0x5e, 0x1b, 0x98, 0x53, 0xc0,
	0x63, 0xa8, 0xad, 0xfc, 0x80, 0xbb, 0x2a, 0xf8, 0xd0, 0x20, 0x1b, 0x49, 0x27, 0x50, 0xcf, 0x8f,
	0x57, 0xf7, 0xdb, 0x32, 0xf2, 0x8d, 0xd4, 0x3e, 0xd4, 0xf3, 0xbe, 0xd2, 0xa9, 0x5b, 0xbc, 0xd6,
	0xde, 0xdd, 0x78, 0x50, 0x43, 0xf1, 0xcf, 0x74, 0x0a, 0x38, 0x00, 0x33, 0xe7, 0x0e, 0xb4, 0x54,
	0x8d, 0x4d, 0x13, 0xb6, 0xf7, 0xb6, 0x44, 0x94, 0x95, 0xa4, 0x0a, 0x33, 0xb7, 0x56, 0x5d, 0x65,
	0x73, 0xd3, 0xed, 0xec, 0x2d, 0x6a, 0xd8, 0x29, 0xcc, 0xab, 0xf2, 0x93, 0x8e, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xb1, 0x16, 0x25, 0x7e, 0xe8, 0x05, 0x00, 0x00,
}
